In [1]:
import pandas as pd
import numpy as np

In [2]:
resume_df = pd.read_csv("../data/resumes/Resume.csv")

resume_df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [3]:
print("Shape:", resume_df.shape)
print("\nColumns:")
print(resume_df.columns.tolist())

Shape: (2484, 4)

Columns:
['ID', 'Resume_str', 'Resume_html', 'Category']

In [4]:
resume_df.isnull().sum()

ID             0
Resume_str     0
Resume_html    0
Category       0
dtype: int64

In [5]:
print("Number of categories:", resume_df["Category"].nunique())

resume_df["Category"].value_counts()

Number of categories: 24

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
CHEF                      118
FINANCE                   118
ENGINEERING               118
ACCOUNTANT                118
FITNESS                   117
AVIATION                  117
SALES                     116
HEALTHCARE                115
CONSULTANT                115
BANKING                   115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [6]:
print(resume_df["Resume_str"].iloc[0][:3000])

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate

HR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding

In [7]:
resume_df["resume_length"] = resume_df["Resume_str"].str.len()

resume_df["resume_length"].describe()

count     2484.000000
mean      6295.308776
std       2769.251458
min         21.000000
25%       5160.000000
50%       5886.500000
75%       7227.250000
max      38842.000000
Name: resume_length, dtype: float64

In [8]:
job_df = pd.read_csv("../data/jobs/monster_com-job_sample.csv")

job_df.head()

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c

In [9]:
print("Shape:", job_df.shape)

print("\nColumns:")
print(job_df.columns.tolist())

Shape: (22000, 14)

Columns:
['country', 'country_code', 'date_added', 'has_expired', 'job_board', 'job_description', 'job_title', 'job_type', 'location', 'organization', 'page_url', 'salary', 'sector', 'uniq_id']

In [10]:
job_df.isnull().sum()

country                0
country_code           0
date_added         21878
has_expired            0
job_board              0
job_description        0
job_title              0
job_type            1628
location               0
organization        6867
page_url               0
salary             18554
sector              5194
uniq_id                0
dtype: int64

In [11]:
job_df["job_description"].iloc[0]

"TeamSoft is seeing an IT Support Specialist to join our client in Madison, WI. The ideal candidate must have at least 6 years of experience in the field. They need to be familiar with a variety of the field's concepts, practices, and procedures as this position relies on extensive experience and judgment to plan and accomplish goals. Required Skills:• Call tracking software• Phone based technical support• Problem documentation and communication• Remote Desktop Management Tools• Respond to customer requests• General understanding of LANDesk• Microsoft Office 2007 SuiteFind out why TeamSoft is the Madison area's technology leader with over 200 IT consultants. Owned, operated, and managed by IT consultants, TeamSoft is the clear choice for your career. Join the TeamSoft family today!Did you know?• TeamSoft offers salaried options for many positions that include 5 weeks PTO and great benefits!• TeamSoft has been in business since 1996• TeamSoft's owners are local IT professionals who possess a wealth of experience in application development, business analysis, and project management• TeamSoft's Recruiters are knowledgeable, friendly, and ready to help you make your next great career move• TeamSoft offers a full benefits suite to all of our W2 consultants, including a 401k plan with a 100% vested 4% dollar for dollar match• Our targeted selection process is designed to get to know your strengths and career interests and provide you with the best chance for success in your new position• Our longest running consultant has been with us for 16 years• Consultants can participate in our charitable giving committee. To date, TeamSoft's charitable giving committee has donated over $100,000!TeamSoft is owned by local IT professionals. Our team also has deep experience with IT staffing. Our clients understand this and rely on our expertise. That is why TeamSoft is the Madison Area's largest privately owned IT consulting firm, with more than 200 current consultants! With over 50 active clients, TeamSoft will give you the greatest exposure to the widest range of IT careers.Our owners possess a combined 60+ years of IT consulting experience. Our recruiting and Account Management staff are very well-versed in our client markets. We get you. We know you. We know what you do every day. And we know what you deal with on the job.You take your career seriously and so do we. At TeamSoft you are not just a resume or number. Our goal is to create long-term partnerships with each of our consultants, and according to feedback from many of them, we are very good at this. Click HERE to see what our consultants have to say about working with TeamSoft.TeamSoft -- Promote yourself!TeamSoft is an equal employment opportunity employer functioning under an Affirmative Action Plan."

In [12]:
job_df["job_title"].value_counts().head(20)

job_title
Monster                                                                                                                            318
Shift Supervisor Job in Camphill                                                                                                   256
RN                                                                                                                                  70
Shift Supervisor - Part-Time Job in Camphill                                                                                        56
Manager                                                                                                                             50
Please apply only if you are qualified.                                                                                             31
ASST STORE MGR Job in Columbus                                                                                                      26
LEAD SALES ASSOCIATE-FT Job in Columbus                                                                                             26
SALES ASSOCIATE Job in Columbus                                                                                                     24
LEAD SALES ASSOCIATE-PT Job in Columbus                                                                                             24
Director                                                                                                                            23
Manufacturing – Change Career to - Truck Driver – Entry Level                                                                       18
Truck Driver – Entry Level ( CDL Not Required ) Transportation – Full Time                                                          18
Registered Nurse                                                                                                                    18
Financial Advisor / Financial Sales Representative- Full Time Sales                                                                 15
General Manager                                                                                                                     15
Security Officer Job in Texas US body { margin:px; overflow: visible !important; } #ejb_header { color: #; font-family: Verdana     14
Personal Banker  Job in Dallas                                                                                                      14
Senior Manager                                                                                                                      14
Staff Accountant Job in Dallas                                                                                                      14
Name: count, dtype: int64

In [13]:
it_resume = resume_df[
    resume_df["Category"] == "INFORMATION-TECHNOLOGY"
]["Resume_str"].iloc[0]

print(it_resume[:3000])

         INFORMATION TECHNOLOGY         Summary     Dedicated  Information Assurance Professional  well-versed in analyzing and mitigating risk and finding cost-effective solutions. Excels at boosting performance and productivity by establishing realistic goals and enforcing deadlines.  Versatile IT professional with 37 years of Enterprise design and engineering methodology.       Skills          Enterprise platforms  Knowledge of Product Lifecycle Management (PLM)  Project tracking  Hardware and software upgrade planning  Product requirements documentation  Self-directed  MS Visio  Decisive  Collaborative  Domain Active Directory Layout  Data storage engineering      Information Assurance  Risk Management Framework (RMF)  Active Directory design and deployment  Workstation build and deployment  Systems Accreditation Packages  Red Hat Enterprise Linux installation and hardening  Network Design & Troubleshooting   High Performance Computing            Experience      Company Name    City  ,   State    Information Technology   02/2011   to   Current        I was hired to manage accreditation
efforts for a major department modernization project involving 3
accreditation packages each leading to successful Authorization To
Operate decisions.  Responsibilities then increased to include all
departmental accreditation efforts leading to another 3 successful
ATOs.  Now, working on 4 new accreditation including
re-authorization for an existing project.  Succeeded in writing and
implementing vulnerability management for existing accredited
systems.





Success
of the accreditation hinged on coordination with ONI Enterprise in
critical design decisions and to help the program integrate smoothly
into the Enterprise thru many meetings, analyzing the Enterprise
business model to understand the best fit for the program.





The
different projects required careful management of specific STIG
compliance and hardening for the different configurations and
services required for the specific domain to be integrated.   Analyzed complex computer systems to assess vulnerability and risk.    Supervised  5  external computer consultants and vendors.    Managed application patches, data backup, security changes and network configuration.           Company Name    City  ,   State    Systems Engineer   02/2006   to   02/2011        I was Hired
to initiate processing strategies in fulfilling department analyst requirements.  Requirements were fulfilled thru i dentifying product problems and strengths and collected data on customer experience  and review of Enterprise compliance to transition to new
technology for supporting new processing needs thru proper processing
power.  The next challenge  came as storage requirements for better performance and more
controlled uses.  After careful study of local infrastructure design, a local storage with off the shelf solutions was
adopted to grow local storage to over 200TB.  In using this solution,
the department saved just over a m

In [14]:
resume_df[
    resume_df["Category"] == "ENGINEERING"
][["Resume_str"]].head(3)

                                             Resume_str
1690           ENGINEERING TECHNICIAN           High...
1691           ENGINEERING ASSISTANT       Summary  ...
1692           ENGINEERING MANAGER       Profile    ...

In [15]:
resume_df[
    resume_df["Category"] == "BUSINESS-DEVELOPMENT"
][["Resume_str"]].head(3)

                                            Resume_str
557           BUSINESS DEVELOPMENT           Summar...
558           BUSINESS DEVELOPMENT           Execut...
559           BUSINESS DEVELOPMENT       Profession...

In [16]:
job_df["job_title"].sample(20, random_state=42).tolist()

['Quality Control Lead Job in Santa Cruz',
 'Case Manager Job in Sunset Point',
 'Sr Manager',
 'Groundskeeper Job in Knoxville',
 'Sales Agent Job in Knoxville',
 'Staff Accountant Job in Dallas',
 'Legal Assistant Job in Plymouth',
 'Shift Supervisor Job in Camphill',
 'Bilingual Spanish Required Retail Sales Consultant Queens West HIT Job in Astoria',
 'B Combat Engineer - Construction and Engineering Specialist Job in Richmond',
 'Chemical Operations Specialist Job in East Flat Rock  body { margin:px; overflow: visible !important; } #ejb_header { color: #; font-family: Verdana',
 'Department Supervisor Job in Cincinnati',
 'Healthcare Benefits Navigator Lead Job in Miami',
 'CBS Specification Sales Manager Job in Dallas',
 'Nurse Practitioner Job in Fremont',
 'Specialty Insurance Underwriter Job in Minneapolis',
 'Operations Lead - Foster City',
 'Sales Consultant - Will Train! Excellent Income Opportunity Job in Columbus',
 'Cook - University of Sioux Falls Job in Sioux Falls',
 'Quality Research Analyst']

In [17]:
skills_df = pd.read_csv("../data/skills/skills_en.csv")

print(skills_df.shape)
print(skills_df.columns.tolist())

skills_df.head()

(13960, 13)
['conceptType', 'conceptUri', 'skillType', 'reuseLevel', 'preferredLabel', 'altLabels', 'hiddenLabels', 'status', 'modifiedDate', 'scopeNote', 'definition', 'inScheme', 'description']

,conceptType,conceptUri,skillType,reuseLevel,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,scopeNote,definition,inScheme,description
0,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0005c151-5b5a...,skill/competence,sector-specific,manage musical staff,manage music staff\ncoordinate duties of music...,NaN,released,2023-11-30T15:53:37.136Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Assign and manage staff tasks in areas such as...
1,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00064735-8fad...,skill/competence,occupation-specific,supervise correctional procedures,manage prison procedures\nmonitor correctional...,NaN,released,2023-11-30T15:04:00.689Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Supervise the operations of a correctional fac...
2,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/000709ed-2be5...,skill/competence,sector-specific,apply anti-oppressive practices,make use of anti-oppressive practices\nuse ant...,NaN,released,2023-11-28T10:45:53.54Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Identify oppression in societies, economies, c..."
3,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0007bdc2-dd15...,skill/competence,sector-specific,control compliance of railway vehicles regulat...,checking compliance with rolling stock regulat...,NaN,released,2023-11-30T16:29:18.273Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Inspect rolling stock, components and systems ..."
4,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00090cc1-1f27...,skill/competence,cross-sector,identify available services,determine available services\nclassify availab...,NaN,released,2023-11-28T10:38:49.206Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Identify the different services available for ...

# ESCO Skill Extraction Prototype

In [18]:
skills_df[[
    "preferredLabel",
    "altLabels"
]].head()

,preferredLabel,altLabels
0,manage musical staff,manage music staff\ncoordinate duties of music...
1,supervise correctional procedures,manage prison procedures\nmonitor correctional...
2,apply anti-oppressive practices,make use of anti-oppressive practices\nuse ant...
3,control compliance of railway vehicles regulat...,checking compliance with rolling stock regulat...
4,identify available services,determine available services\nclassify availab...

In [19]:
esco_skills = (
    skills_df["preferredLabel"]
    .dropna()
    .str.lower()
    .unique()
)

print("Number of skills:", len(esco_skills))

Number of skills: 13939

In [20]:
import random

random.sample(
    list(esco_skills),
    20
)

['milling machines',
 'ensure adequate conditions in wine cellars',
 'assist cage net changing',
 'hydrography',
 'manage emergency situations on board',
 'monitor swimming-pool infrastructure',
 'operate telescopes',
 'use traditional carpet making techniques',
 'remove roofs',
 'document security incidents in the store',
 'define roles of supporting team for community arts programme',
 'maintain costumes',
 'examine conservation issues',
 'tend to elderly people',
 'use casts of body parts',
 'conduct a homeopathic consultation',
 'horary astrology',
 'monitor customer safety on apron',
 'excavation techniques',
 'perform dental radiographs']

In [21]:
tech_keywords = [
    "python",
    "sql",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "nlp",
    "data analysis",
    "data science",
    "artificial intelligence",
    "aws",
    "cloud computing",
    "docker",
    "kubernetes",
    "java",
    "javascript",
    "react",
    "node.js"
]

for skill in tech_keywords:
    matches = skills_df[
        skills_df["preferredLabel"]
        .str.contains(skill, case=False, na=False)
    ]

    print(f"\n{skill}: {len(matches)} matches")

    if len(matches) > 0:
        print(matches["preferredLabel"].head(5).tolist())

python: 1 matches
['Python (computer programming)']

sql: 7 matches
['MySQL', 'SQL', 'SQL', 'SQL Server Integration Services', 'NoSQL']

machine learning: 2 matches
['machine learning', 'utilise machine learning']

deep learning: 1 matches
['deep learning']

tensorflow: 0 matches

pytorch: 0 matches

nlp: 0 matches

data analysis: 5 matches
['perform online data analysis', 'perform data analysis', 'use methods of logistical data analysis', 'perform safety data analysis', 'use specific data analysis software']

data science: 1 matches
['data science']

artificial intelligence: 1 matches
['principles of artificial intelligence']

aws: 15 matches
['laws on the transportation of dangerous goods', 'types of table saws', 'types of crosscut saws', 'detect flaws in pipeline infrastructure', 'road traffic laws']

cloud computing: 0 matches

docker: 0 matches

kubernetes: 0 matches

java: 8 matches
['write Javanese', 'understand written Javanese', 'Java (computer programming)', 'JavaScript', 'Javanese']

javascript: 2 matches
['JavaScript', 'JavaScript Framework']

react: 16 matches
['chemical reactions of roasting cacao beans', 'allergic cosmetics reactions', 'maintain nuclear reactors', 'react to mining emergencies', "recognise patients' reaction to therapy"]

node.js: 0 matches

In [22]:
import sys
sys.path.append("../")
from src.skill_extractor import SkillExtractor

In [23]:
extractor = SkillExtractor(
    "../data/skills/skills_en.csv"
)

In [24]:
sample_text = """
Built machine learning models using Python,
TensorFlow and SQL.
Experience with Docker and AWS.
"""

extractor.extract_skills(sample_text)

['aws', 'docker', 'machine learning', 'python', 'sql', 'tensorflow']

In [25]:
real_resume = resume_df["Resume_str"].iloc[0]

skills = extractor.extract_skills(real_resume)

print("Number of extracted skills:", len(skills))
print(skills[:100])

Number of extracted skills: 11
['accounting', 'company policies', 'customer service', 'data analysis', 'financial management', 'medical terminology', 'plan', 'public relations', 'sales strategies', 'statistics', 'terminology']

In [26]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [27]:
from sentence_transformers import util

resume_text = resume_df["Resume_str"].iloc[0]

job_description = """
Cybersecurity Analyst

Requirements:
- Risk assessment
- Vulnerability management
- Security compliance
- Information assurance
- System security
"""

In [28]:
resume_embedding = model.encode(
    resume_text,
    convert_to_tensor=True
)

job_embedding = model.encode(
    job_description,
    convert_to_tensor=True
)

similarity = util.cos_sim(
    resume_embedding,
    job_embedding
)

print(float(similarity))

0.2727266550064087

In [29]:
cyber_resume = """
Information Assurance Professional
Vulnerability Management
Risk Assessment
Security Accreditation
Security Compliance
Information Security
"""

cyber_embedding = model.encode(
    cyber_resume,
    convert_to_tensor=True
)

job_embedding = model.encode(
    job_description,
    convert_to_tensor=True
)

similarity = util.cos_sim(
    cyber_embedding,
    job_embedding
)

print(float(similarity))

0.7445739507675171

In [30]:
it_resume = resume_df[
    resume_df["Category"] == "INFORMATION-TECHNOLOGY"
]["Resume_str"].iloc[0]

hr_resume = resume_df[
    resume_df["Category"] == "HR"
]["Resume_str"].iloc[0]

bd_resume = resume_df[
    resume_df["Category"] == "BUSINESS-DEVELOPMENT"
]["Resume_str"].iloc[0]

In [31]:
cyber_jd = """
Cybersecurity Analyst

Requirements:
- Vulnerability Management
- Risk Assessment
- Security Compliance
- Information Assurance
- Security Operations
"""

In [32]:
it_emb = model.encode(it_resume, convert_to_tensor=True)
hr_emb = model.encode(hr_resume, convert_to_tensor=True)
bd_emb = model.encode(bd_resume, convert_to_tensor=True)

jd_emb = model.encode(cyber_jd, convert_to_tensor=True)

In [33]:
print("IT:", float(util.cos_sim(it_emb, jd_emb)))
print("HR:", float(util.cos_sim(hr_emb, jd_emb)))
print("Business:", float(util.cos_sim(bd_emb, jd_emb)))

IT: 0.5129294991493225
HR: 0.28040629625320435
Business: 0.21683143079280853

In [34]:
from src.matcher import SemanticMatcher

matcher = SemanticMatcher()

score = matcher.similarity_score(
    it_resume,
    cyber_jd
)

print(score)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

0.5129294991493225

In [35]:
from src.scorer import CandidateScorer

scorer = CandidateScorer()

score = scorer.final_score(
    semantic_similarity=0.51,
    skill_overlap=0.80
)

print(score)

0.597

In [36]:
from src.ranker import ResumeRanker

ranker = ResumeRanker(
    "../data/skills/skills_en.csv"
)

resumes = [
    it_resume,
    hr_resume,
    bd_resume
]

job_description = """
Cybersecurity Analyst

Requirements:
- Risk assessment
- Vulnerability management
- Security compliance
- Information assurance
- System security
"""

results = ranker.rank_candidates(
    resumes,
    job_description
)

results

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

[{'candidate_id': 1,
  'semantic_score': 0.525,
  'skill_score': 0.0,
  'final_score': 0.367,
  'matched_skills': ['data storage',
   'desktop publishing',
   'risk management',
   'sensors'],
  'missing_skills': ['vulnerability management',
   'information assurance',
   'risk assessment',
   'system security',
   'security compliance']},
 {'candidate_id': 2,
  'semantic_score': 0.273,
  'skill_score': 0.0,
  'final_score': 0.191,
  'matched_skills': ['accounting',
   'company policies',
   'customer service',
   'data analysis',
   'financial management',
   'medical terminology',
   'plan',
   'public relations',
   'sales strategies',
   'statistics',
   'terminology'],
  'missing_skills': ['vulnerability management',
   'information assurance',
   'risk assessment',
   'system security',
   'security compliance']},
 {'candidate_id': 3,
  'semantic_score': 0.208,
  'skill_score': 0.0,
  'final_score': 0.145,
  'matched_skills': ['customer service',
   'gas market',
   'legal studies',
   'logistics',
   'market analysis',
   'outdoor advertising',
   'statistics',
   'strategic planning'],
  'missing_skills': ['vulnerability management',
   'information assurance',
   'risk assessment',
   'system security',
   'security compliance']}]

In [37]:
required_skills = ranker.extractor.extract_skills(
    job_description
)

print(required_skills)
print(len(required_skills))

[]
0

In [38]:
print(len(extractor.skills))

13959

In [39]:
extractor.extract_skills("""
Python
SQL
Machine Learning
Docker
AWS
TensorFlow
""")

['aws', 'docker', 'machine learning', 'python', 'sql', 'tensorflow']

In [40]:
extractor.extract_skills("""
Risk Assessment
Vulnerability Management
Security Compliance
Information Assurance
System Security
""")

[]

In [41]:
import spacy

nlp = spacy.load("en_core_web_sm")

text = """
Cybersecurity Analyst

Requirements:
- Vulnerability Management
- Risk Assessment
- Security Compliance
- Information Assurance
"""

doc = nlp(text)

for chunk in doc.noun_chunks:
    print(chunk.text)

Cybersecurity Analyst

Requirements
- Vulnerability Management
- Risk Assessment
- Security Compliance
- Information Assurance

In [42]:
from src.phrase_extractor import PhraseExtractor

phrase_extractor = PhraseExtractor()

phrase_extractor.extract_phrases("""
Cybersecurity Analyst

Requirements:
- Vulnerability Management
- Risk Assessment
- Security Compliance
- Information Assurance
""")

['information assurance',
 'risk assessment',
 'security compliance',
 'vulnerability management']

In [43]:
required_skills = set(
    extractor.extract_skills(job_description)
)

required_skills.update(
    phrase_extractor.extract_phrases(
        job_description
    )
)

print(required_skills)

{'vulnerability management', 'information assurance', 'risk assessment', 'system security', 'security compliance'}

In [44]:
required_skills = set(
    ranker.extractor.extract_skills(job_description)
)

required_skills.update(
    ranker.phrase_extractor.extract_phrases(
        job_description
    )
)

print(required_skills)
print(len(required_skills))

{'vulnerability management', 'information assurance', 'risk assessment', 'system security', 'security compliance'}
5

In [45]:
results = ranker.rank_candidates(
    resumes,
    job_description
)

results

[{'candidate_id': 1,
  'semantic_score': 0.525,
  'skill_score': 0.0,
  'final_score': 0.367,
  'matched_skills': ['data storage',
   'desktop publishing',
   'risk management',
   'sensors'],
  'missing_skills': ['vulnerability management',
   'information assurance',
   'risk assessment',
   'system security',
   'security compliance']},
 {'candidate_id': 2,
  'semantic_score': 0.273,
  'skill_score': 0.0,
  'final_score': 0.191,
  'matched_skills': ['accounting',
   'company policies',
   'customer service',
   'data analysis',
   'financial management',
   'medical terminology',
   'plan',
   'public relations',
   'sales strategies',
   'statistics',
   'terminology'],
  'missing_skills': ['vulnerability management',
   'information assurance',
   'risk assessment',
   'system security',
   'security compliance']},
 {'candidate_id': 3,
  'semantic_score': 0.208,
  'skill_score': 0.0,
  'final_score': 0.145,
  'matched_skills': ['customer service',
   'gas market',
   'legal studies',
   'logistics',
   'market analysis',
   'outdoor advertising',
   'statistics',
   'strategic planning'],
  'missing_skills': ['vulnerability management',
   'information assurance',
   'risk assessment',
   'system security',
   'security compliance']}]